image: grafana/k6

stages:
  - test
  - report

test:
  stage: test
  variables:
    K6_OUT: influxdb=http://iam-qa-01.test.env:8086/k6
  script:
    - k6 run ./scenarios/project/task3.js --insecure-skip-tls-verify
  artifacts:
    when: always
    paths:
      - result.html
  tags:
    - test.env

pages:
  stage: report
  dependencies:
    - test
  script:
    - cp result.html public/
  artifacts:
    paths:
      - public
    expire_in: 14 days
  when: manual

